sudo: required
language: python
python:
  - "3.6"
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install PyYAML==5.3
script:
  # Check that all files are built and up-to-date.
  - python manage.py check_updated
